# Generated by Django 3.0 on 2020-01-05 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allpolishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='naildetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=500)),
                ('nailtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NailPolishes.Allpolishes')),
            ],
        ),
    ]
