# Generated by Django 3.0 on 2020-01-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NailPolishes', '0002_auto_20200107_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naildetails',
            old_name='nailtype',
            new_name='polishtype',
        ),
    ]
