# Generated by Django 3.0 on 2020-01-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NailPolishes', '0003_auto_20200107_1303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='naildetails',
            new_name='polishdetails',
        ),
    ]
