# Generated by Django 3.0 on 2020-01-07 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NailPolishes', '0004_auto_20200107_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polishdetails',
            old_name='description',
            new_name='nailtype',
        ),
        migrations.RemoveField(
            model_name='polishdetails',
            name='size_available',
        ),
        migrations.AddField(
            model_name='allpolishes',
            name='startedfrom',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 22, 24, 4, 375963, tzinfo=utc), verbose_name='startedfrom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polishdetails',
            name='your_choice',
            field=models.BooleanField(default=False),
        ),
    ]
