# Generated by Django 3.0 on 2020-01-07 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NailPolishes', '0005_auto_20200107_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allpolishes',
            name='startedfrom',
        ),
    ]
