# Generated by Django 3.0 on 2020-01-07 23:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NailPolishes', '0006_remove_allpolishes_startedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpolishes',
            name='startedfrom',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 23, 37, 58, 100472, tzinfo=utc), verbose_name='startedfrom'),
            preserve_default=False,
        ),
    ]
